In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# step 1 : create a synthetic data
X,y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [7]:
# convert to tensors
X = torch.tensor(X,dtype=float)
y = torch.tensor(y,dtype=float)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)

In [9]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.], dtype=torch.float64)

In [10]:
from torch.utils.data import Dataset,DataLoader

In [11]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):

        self.features = features
        self.labels = labels
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [12]:
dataset = CustomDataset(X,y)

In [15]:
len(dataset)

10

In [17]:
dataset[3]

(tensor([-0.7206, -0.9606], dtype=torch.float64),
 tensor(0., dtype=torch.float64))

## Data loader

In [18]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [20]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*50)

tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
__________________________________________________
tensor([[ 1.7273, -1.1858],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
__________________________________________________
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
__________________________________________________
tensor([[-0.5872, -1.9717],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([0., 0.], dtype=torch.float64)
__________________________________________________
tensor([[-1.9629, -0.9923],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
__________________________________________________
