In [1]:
import torch
print(torch.__version__)

2.5.1


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"CUDA is available:- {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available")

GPU is available
CUDA is available:- GeForce GTX 1650


## Creating a Tensor

In [5]:
# using Empty

a = torch.empty(2,3)

In [6]:
# cheack type
type(a)

torch.Tensor

In [7]:
# using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using Ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand 

torch.rand(2,3)

tensor([[0.9776, 0.3542, 0.1015],
        [0.4748, 0.7969, 0.4614]])

In [10]:
# using of seed 

torch.rand(2,3)

tensor([[0.0908, 0.6320, 0.8022],
        [0.7598, 0.1955, 0.7007]])

In [11]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange

print('using arange-> ',torch.arange(0,10))

# using linespace
print('using linespace-> ',torch.linspace(0,10,10))

# using eye
print('using eye-> ',torch.eye(3))

# using full
print('using full-> ',torch.full((3,3),5))

using arange->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linespace->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensors Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[4082328799536,             0,             0],
        [            0,             0,             0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

## Tensor Data Types

In [22]:
# find data types
x.dtype

torch.int64

In [23]:
# assign Data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
# usint to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical operations

### 1. Sclar operation

In [28]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [35]:
# addition 
x + 2

# subtracion
x - 2

# multiplication
x * 2

# division 
x / 3

# int division
(x * 100) // 3

# mod
((x * 100) // 3)%2

# power

x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [39]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [40]:
# Addition
a + b

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [41]:
# subtracion
a - b

tensor([[ 0.2257,  0.4794, -0.4258],
        [-0.4592,  0.6280, -0.4667]])

In [42]:
# Multiplicaion
a * b

tensor([[0.0041, 0.1547, 0.5032],
        [0.1746, 0.1288, 0.3770]])

In [43]:
# division
a / b

tensor([[14.3533,  3.1705,  0.5534],
        [ 0.3499,  4.8557,  0.4757]])

In [44]:
# mod 
a % b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [45]:
c = torch.tensor([1,-2,3,-5])

In [46]:
# abs 
torch.abs(c)

tensor([1, 2, 3, 5])

In [47]:
# negative 
torch.neg(c)

tensor([-1,  2, -3,  5])

In [48]:
d = torch.tensor([1.9,2.3])

In [49]:
# round
torch.round(d)

tensor([2., 2.])

In [50]:
# ceil
torch.ceil(d)

tensor([2., 3.])

In [51]:
# floor
torch.floor(d)

tensor([1., 2.])

In [52]:
# clamp
torch.clamp(d, min=2, max=3)


tensor([2.0000, 2.3000])

### 3. Reduction Operation

In [53]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[5, 7, 5],
        [9, 9, 7]])

In [54]:
# sum
torch.sum(e)

tensor(42)

In [55]:
# sum along column
torch.sum(e, dim=0)

tensor([14, 16, 12])

In [56]:
# sum along row
torch.sum(e,dim=1)

tensor([17, 25])

In [58]:
# mean
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.mean(e)

tensor(7.8333)

In [59]:
# mean along col
torch.mean(e,dim=0)

tensor([7.0000, 8.0000, 8.5000])

In [60]:
# median
torch.median(e)

tensor(8.)

In [61]:
# max 
torch.max(e)

tensor(9.)

In [62]:
# min
torch.min(e)

tensor(5.)

In [63]:
# product
torch.prod(e)


tensor(204120.)

In [64]:
# standart deviation
torch.std(e)

tensor(1.6021)

In [65]:
#variance
torch.var(e)

tensor(2.5667)

In [66]:
# argmax
torch.argmax(e)

tensor(1)

In [67]:
# argmin
torch.argmin(e)


tensor(0)

### 4. Matrix Operations

In [68]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(2,3),low=0,high=10)
print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1, 5],
        [5, 0, 4]])


In [70]:
# matrix multiplication
torch.matmul(f,g.T)

tensor([[53, 38],
        [65, 47]])

In [71]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

# dot product
torch.dot(vector1,vector2)

tensor(32)

In [74]:
# transpose
torch.transpose(f,0,1)

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [76]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [77]:
# determinant
torch.det(h)

tensor(-6.)

In [78]:
# inversse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5. Comparision Operations

In [79]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [80]:
# greate than
i > j

tensor([[False,  True, False],
        [ True, False, False]])

In [81]:
# less than
i < j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [82]:
i == j 

tensor([[False, False, False],
        [False, False, False]])

In [83]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special Fucntions

In [90]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [91]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [92]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [93]:
# sprt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [94]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [95]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [96]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

## Inplace Operations

In [97]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [98]:
m + n

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [99]:
m.add(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [100]:
m

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [101]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [102]:
torch.relu(m)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
# permanent Changes
m.relu_()

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [104]:
m

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

## Copying a Tensor

In [106]:
a = torch.rand(2,3)
a 

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [107]:
b = a

In [108]:
b

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [109]:
a[0][0] = 0
a

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [110]:
b

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [111]:
id(a)

2598722425920

In [112]:
id(b)

2598722425920

In [113]:
b = a.clone()

In [114]:
a

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [115]:
b

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [116]:
a[0][0] = 2

In [117]:
a

tensor([[2.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [118]:
b

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

## Tensor Operation on GPU

In [119]:
torch.cuda.is_available()

True

In [120]:
device = torch.device('cuda')

In [121]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [122]:
# moving existing tensor on GPU
a

tensor([[2.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [124]:
b = a.to(device=device)

In [125]:
b

tensor([[2.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]], device='cuda:0')

In [126]:
b + 5

tensor([[7.0000, 5.4847, 5.9436],
        [5.3904, 5.2499, 5.3206]], device='cuda:0')

In [131]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# measure time on CPU

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# move matrix to GPU
matrix_gpu1 = matrix_cpu1.to(device=device)
matrix_gpu2 = matrix_cpu2.to(device=device)

# measure time on GPU

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() # ensure all operation are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

print("\n SpeedUp (cpu time/ GPU time):",cpu_time//gpu_time)


Time on CPU: 8.6575 seconds
Time on GPU: 1.5644 seconds

 SpeedUp (cpu time/ GPU time): 5.0


## Reshaping Tensors

In [133]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [134]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [135]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [137]:
b = torch.rand(2,3,4)
b

tensor([[[0.7564, 0.2475, 0.9327, 0.3792],
         [0.7587, 0.8470, 0.9411, 0.2964],
         [0.0847, 0.9972, 0.9092, 0.7648]],

        [[0.2931, 0.2471, 0.5781, 0.3772],
         [0.8885, 0.5652, 0.0254, 0.7406],
         [0.8800, 0.1282, 0.2993, 0.2657]]])

In [139]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [140]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape


torch.Size([1, 226, 226, 3])

In [141]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [142]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [145]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Torch

In [146]:
import numpy as np

In [147]:
a = torch.tensor([1,2,3])

In [149]:
b = a.numpy()

In [150]:
b

array([1, 2, 3])

In [151]:
type(b)

numpy.ndarray

In [152]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [153]:
torch.from_numpy(c)

tensor([1, 2, 3])