In [1]:
# Create model class

import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear(features) # z = wx + b
        out = self.sigmoid(out) 

        return out

### Dense model

In [ ]:
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU() # activation
        self.linear2 = nn.Linear(3,1) # hidden layer
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        
        out = self.linear1(features) # z = wx + b
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out) 

        return out

### Sequential container

In [20]:
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self,features):
        
        out = self.network(features)

        return out

In [21]:
# create dataset

features = torch.rand(10,5)

# create model
model = Model(num_features=5)


# call the forward pass
# model.forward()
model(features)

tensor([[0.6002],
        [0.5840],
        [0.5781],
        [0.5841],
        [0.6038],
        [0.5847],
        [0.5851],
        [0.5845],
        [0.5943],
        [0.5746]], grad_fn=<SigmoidBackward0>)

In [17]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.3636, -0.0557, -0.0007, -0.2336, -0.3018],
        [-0.1427, -0.1969, -0.1184,  0.1515,  0.4249],
        [ 0.0587, -0.1842,  0.0607, -0.2005,  0.1905]], requires_grad=True)

In [18]:
model.linear2.bias

Parameter containing:
tensor([0.2054], requires_grad=True)

In [19]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00